"""
Les constantes nécessaires au fonctionnement du jeu
"""

SCREEN_WIDTH = 256+0 # bust be improved before
GAME_SCREEN_WIDTH = 256
SCREEN_HEIGHT = 256
GAME_SCREEN_HEIGHT = 256
GAME_SCREEN_WIDTH_START = SCREEN_WIDTH-GAME_SCREEN_WIDTH

START_POSITION_X = GAME_SCREEN_WIDTH_START + GAME_SCREEN_WIDTH//2
START_POSITION_Y = 200

SCORE_DESTROYER = 50
SCORE_DRONE_ALONE = 100
SCORE_DRONE_SPEED1 = 200
SCORE_SPIDRONE = 300 # not implemented
SCORE_DRONE_SPEED2 = 400
SCORE_TURRET = 500 # not implemented
SCORE_BOSS = 600 # not implemented
SCORE_VICTOIRE = 650

BASE_LIFE = 30

PLAYER_LIFE = 6
PLAYER_SPEED = 2

DESTROYER_LIFE = 8
DESTROYER_FIRE_RATE = 20
DESTROYER_SPAWN_RATE = 20

SHIELD_POWER = 4
SHIELD_DURATION = 20
SHIELD_RELOAD = 40

DURATION_STIMS = 10

ROCKET_RELOAD = 5

TAILLE_EXPLOSION = 3

MAX_DETECTOR_DURATION = 30

GAME_SPEED = 1 # never put under 0.5

TIME_NPC_SPEAK = 30